language: android
jdk:
- oraclejdk8
android:
  components:
  #Use latest revision of Android SDK tools
  - platform-tools
  - tools

  #Build tools version used by the project
  - build-tools-25.0.2

  #SDK version used to compile the project
  - android-25
script:
- "./gradlew test"