language: android
jdk:
- oraclejdk8
android:
  components:
  #Use latest revision of Android SDK tools
  - platform-tools
  - tools

  #Build tools version used by the project
  - build-tools-23.0.3

  #SDK version used to compile the project
  - android-23
script:
- "./gradlew test"